### ISSUE TITLE
Encounter RuntimeError when compile CUDA layers for PointNet++

### ISSUE THREAD

**Issue by jianghaojun** [sega-hsj/MVT-3DVG#1]
My pytorch version is py3.8_cuda11.1_cudnn8.0.5_0 and I encounter the RuntimeError when compile CUDA layers for PointNet++. 

Solution: I solve this by replacing all mentions of AT_CHECK with TORCH_CHECK in ./referit3d/external_tools/pointnet2/_ext_src/src.

**Comment by sega-hsj** [comment]
Yes, under the cuda11 environment, you should replace all AT_CHECK with TORCH_CHECK for compilation.
