### ISSUE TITLE
Question about motivation. Generating different view by rotating only the center of object is not intuitive.

### ISSUE THREAD

**Issue by jianghaojun** [sega-hsj/MVT-3DVG#2]
Great work on pushing the performance of 3D-VG models to a new level! 

In my perspective, it is unnatural to representing different view by only one point (center of object according to the paper). Thus, I am really curious about the motivation. 

How about the generating different view by rotating all the points of an object and use these different views to conduct experiments? Can this work or not?

Looking forward to author's reply~

**Comment by sega-hsj** [comment]
Thank you for your interest.

After feature extraction of each object by PointNet++, the category and attribute information is extracted but the location information is weak. Therefore most work will add positional encoding to enhance the location information.
 
In our work, our location information is generated by mapping the center point to high dimensional space. Therefore, to generate location information under multiple-view, we only need to rotate the center point.

rotating all points into the multi-view space can achieve similar results, but more computation will need for point cloud feature extraction.
