### ISSUE TITLE
Are there ready-made visualization tools to generate the results shown in Figure 4?

### ISSUE THREAD

**Issue by jianghaojun** [sega-hsj/MVT-3DVG#3]
I find a visualization code in [ScanRefer](https://github.com/daveredrum/ScanRefer/blob/master/scripts/visualize.py). Did you use this code to visualize your results?

**Comment by sega-hsj** [comment]
Hi, we use Open3D for the visualization in our paper.

**Comment by jianghaojun** [comment]
Thanks for your reply. Is this one https://github.com/isl-org/Open3D ？

**Comment by sega-hsj** [comment]
Yes, you can draw point cloud scene and 3D box using this.

**Comment by Zhang-Jing-Xuan** [comment]
Can you release detailed code for visualization with Open3D? Thanks.
