### ISSUE TITLE
How large is the computation?

### ISSUE THREAD

**Issue by Pixie8888** [sega-hsj/MVT-3DVG#4]
Hi,
Thanks for sharing the code! Can I know how large is the computation? Is is computation expensive to do 3D visual grounding?

**Comment by jianghaojun** [comment]
@Pixie412 1 or 2 RTX3090 GPU is enough to run the experiment.

**Comment by Pixie8888** [comment]
I see. I have another question: it seems that you only report the validation accuracy on the ScanRefer benchmark?

**Comment by sega-hsj** [comment]
> I see. I have another question: it seems that you only report the validation accuracy on the ScanRefer benchmark?

Since Scanrefer does not have such severe view-dependent issues as Referit3d, we focus on Referit3D more and only report validation accuracy on Scanrefer. we will test the results on the test set later.
