### ISSUE TITLE
How to visualize with Open3D?

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [sega-hsj/MVT-3DVG#5]
Can you release detailed code for visualization with Open3D? I have obtained test_resultall_vis.pkl in logs/checkpoints. Thanks.

**Comment by Zhang-Jing-Xuan** [comment]
How to visualize the 3D bounding box? Thanks.

**Comment by sega-hsj** [comment]
I draw the 3D bounding box using 'Draw line set' in Open3D, you can refer to the doc: http://www.open3d.org/docs/latest/tutorial/Basic/visualization.html

My visualization process is a little bit trivial so I don't release it.

**Comment by Zhang-Jing-Xuan** [comment]
OK
