### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by ZiyuGuo99** [sega-hsj/MVT-3DVG#6]
Thanks for your wonderful work. : )

May I ask how I could directly visualize the prediction, i.e. bounding box of a certain object,  of an input scene sample? 
I've found some code concerning visualization in function 'detailed_predictions_on_dataset' ([referit3d_net_utils.py](https://github.com/sega-hsj/MVT-3DVG/blob/main/referit3d/models/referit3d_net_utils.py), line 176), but after checking I think it may not realize what I want.

Thanks!

**Comment by sega-hsj** [comment]
you can use Open3D for visualization, it provides tools for visualizing the point cloud scene and drawing 3D boxes.

I didn't release those codes because they are a little bit messy.
