### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by wudongming97** [sega-hsj/MVT-3DVG#7]
Hi,

I have a naive problem with these two benchmarks. They both build upon ScanNet. Should I download the entire dataset (1.3TB)? Or only a part of them are used?

**Comment by eslambakr** [comment]
Hi,

Only selected files (130 GB)
Please follow the documentation from Referit3D paper
https://github.com/referit3d/referit3d/blob/eccv/referit3d/data/scannet/README.md

I hope this answer your question.
