### ISSUE TITLE
the error of Parallel Training 

### ISSUE THREAD

**Issue by Ivan-Tang-3D** [sega-hsj/MVT-3DVG#8]
Thanks for your excellent work!
 I found the batch["lang_tokens'](created in referit_3d_net_utils.py single_epoch_train funtion) not partitioned into 2 parts in model when I used 2 gpus, which resulted in the mismatch of LANG_LOGITS computation(referit_3d_net.py forward function).
So I wonder what I need to revise if I want to use nn.DataParallel.
Looking forward to your reply and I'm sorry if it was my mistake. : )

**Comment by ZiyuGuo99** [comment]
The same question. 
@sega-hsj : Await your reply concerning the above request.

**Comment by ZheningHuang** [comment]
same question here

**Comment by sega-hsj** [comment]
Hi, here we provide a new branch [multigpu-dev](https://github.com/sega-hsj/MVT-3DVG/tree/multigpu-dev).
This branch supports parallel training.
