### ISSUE TITLE
will model checkpoint be released

### ISSUE THREAD

**Issue by ZheningHuang** [sega-hsj/MVT-3DVG#9]
Hi, I wonder if the SOTA result model's checkpoint will be released for evaluation purpose?

Best,
Zhening

**Comment by sega-hsj** [comment]
Here we provide our checkpoints for Nr3d and Sr3d, which can reproduce the paper results.

https://drive.google.com/file/d/1ik-4Pbg2c69ufOcKl_bCHKmIbs8dL1ZD/view?usp=sharing
https://drive.google.com/file/d/1x4tCeHcdyo4p-JFnVnlHNlemPF6sWGWV/view?usp=sharing

The checkpoints include detailed configs and logs.
